parameters:
    database_driver: {{ pillar['parameters']['database_driver'] }}
    database_host: {{ pillar['parameters']['database_host'] }}
    database_port: {{ pillar['parameters']['database_port'] }}
    database_name: {{ pillar["mysql"]["database"] }}
    database_user: {{ pillar["mysql"]["user"] }}
    database_password: {{ pillar["mysql"]["password"] }}
    mailer_transport: {{ pillar['parameters']['mailer_transport'] }}
    mailer_host: {{ pillar['parameters']['mailer_host'] }}
    mailer_user: {{ pillar['parameters']['mailer_user'] }}
    mailer_password: {{ pillar['parameters']['mailer_password'] }}
    locale: {{ pillar['parameters']['locale'] }}
    secret: {{ pillar['parameters']['secret'] }}
